mavros_led:
  ros__parameters:
    events: 
      no_mavros:
        effect: blink_fast
        b: "255"
        priority: "9"
        duration: "0.1"
      emergency_stop_topic:
        effect: blink_fast
        r: "255"
        priority: "9"
        duration: "0.1"
      acro: 
        b: "0"
        g: "155"
        r: "245"
      altctl: 
        b: "40"
        g: "255"
        r: "255"
      connected: 
        effect: rainbow
      disconnected: 
        b: "50"
        effect: blink
        g: "50"
        r: "255"
      error: 
        b: "0"
        effect: flash
        g: "0"
        r: "255"
      offboard: 
        b: "250"
        g: "20"
        r: "220"
      posctl: 
        b: "220"
        g: "100"
        r: "50"
      stabilized: 
        b: "50"
        g: "180"
        r: "30"
      startup: 
        b: "255"
        g: "255"
        r: "255"
