/**:
  ros__parameters:
    events: 
      no_mavros:
        effect: blink_fast
        b: "255"
        priority: "9"
        duration: "2"
      emergency_stop_topic:
        effect: blink_fast
        r: "255"
        brightness: "255"
        priority: "9"
        duration: "2"
      armed:
        effect: blink_fast
        g: "150"
        priority: "1"
        duration: "2.0"
      disarmed:
        effect: blink_fast
        g: "150"
        r: "102"
        priority: "1"
        duration: "2.0"
      acro: 
        b: "0"
        g: "155"
        r: "245"
      altctl: 
        b: "40"
        g: "255"
        r: "255"
      manual:
        b: "40"
        g: "100"
        r: "200"
      connected: 
        effect: rainbow
        duration: "5.0"
        priority: "1"
      disconnected: 
        b: "50"
        effect: blink
        g: "50"
        r: "255"
        duration: "5.0"
        priority: "1"
      error: 
        b: "0"
        effect: flash
        g: "0"
        r: "255"
      offboard: 
        b: "250"
        g: "20"
        r: "220"
      posctl: 
        b: "220"
        g: "100"
        r: "50"
      stabilized: 
        b: "50"
        g: "180"
        r: "30"
      startup: 
        b: "255"
        g: "255"
        r: "255"
      auto.land:
        effect: wipe
        r: "153"
        g: "153"

