name: 'Update images'

on:
  # Triggers on push to any tag of form vX.X.X
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
   #
  # Call bake for each controller image in sequence
  #
  bake_controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (starling-clover)
        uses: docker/bake-action@master
        with:
          files: |
            ./docker-bake.hcl
          targets: |
            starling-clover
          push: true
        env:
          BAKE_VERSION: ${{ steps.tag_name.outputs.GITHUB_TAG }}
          BAKE_RELEASENAME: latest
          BAKE_CACHETO_NAME: cache
          BAKE_CACHEFROM_NAME: cache
